/** @format */

import styles from './styles/RouteInfo.Module.css';
import Button from '../../common/Button';

function RouteInfo(props) {
    const games = require('../../../resources/gamesList.json');
    const routes = require('../../../notes/routes.json');

    return (
        <div className={`${styles.routeInfo}`}>
            <h2>Update your Route</h2>
            <input
                type="text"
                name="title"
                className={`${styles.textInput}`}
                placeholder="Title"
                defaultValue={props.title}
                onBlur={props.handleInputChange}
            />
            <input
                type="text"
                name="path"
                className={`${styles.textInput}`}
                placeholder="Path"
                defaultValue={props.path}
                onBlur={props.handleInputChange}
            />
            <select
                name="game"
                className={`${styles.select}`}
                value={props.game}
                onChange={props.handleInputChange}>
                <option value="">Select a game</option>
                {games.map((game) => (
                    <option key={game} value={game}>
                        {routes[game].name}
                    </option>
                ))}
            </select>
            <div className="row">
                <div>
                    Import Text:{' '}
                    <input
                        type="file"
                        name={'textImport'}
                        onChange={props.handleInputChange}
                    />
                </div>
                <div>
                    Import JSON:{' '}
                    <input
                        type="file"
                        name={'jsonImport'}
                        onChange={props.handleInputChange}
                    />
                </div>
                <Button
                    text="Load Last Edit"
                    size="medium"
                    onClick={props.loadLastRouteEdit}
                />
                <Button
                    text="Generate JSON File"
                    size="medium"
                    onClick={props.generateDownload}
                />
                <Button
                    text="Preview Route"
                    size="medium"
                    onClick={props.swapPreview}
                />
            </div>

            <div className={`${styles.instructions}`}>
                <h3>How to Use</h3>
                <ul>
                    <li>Fill out information about your route above.</li>
                    <li>
                        If you have a text file, separate each "Section" by new
                        lines. Upload it via the import option above.
                    </li>
                    <li>
                        If you have an existing JSON file generated by the tool,
                        upload it via the import option above.
                    </li>
                    <li>
                        When you are done (or need to save your progress), click
                        the Generate JSON file button, then click Create JSON
                        link to save your file.
                    </li>
                    <li>
                        When your route is ready, create a new branch of the{' '}
                        <a
                            href="https://github.com/RischDev/rischdev.github.io"
                            target="_blank"
                            rel="noreferrer">
                            notes repository
                        </a>
                        . Follow the instructions in the README.
                    </li>
                </ul>
            </div>
        </div>
    );
}

export default RouteInfo;
